// Core v4.8 patch: Bard, Druid, Sorcerer and Warlock progression through level 5.
const V48_FULL_SLOTS={1:{1:2},2:{1:3},3:{1:4,2:2},4:{1:4,2:3},5:{1:4,2:3,3:2}};
const V48_WARLOCK_SLOTS={1:{1:1},2:{1:2},3:{2:2},4:{2:2},5:{3:2}};
const V48_KNOWN={bard:{1:4,2:5,3:6,4:7,5:8},sorcerer:{1:2,2:3,3:4,4:5,5:6},warlock:{1:2,2:3,3:4,4:5,5:6}};
const V48_CANTRIPS={bard:{1:2,4:3},druid:{1:2,2:3,4:4},sorcerer:{1:4,4:5},warlock:{1:2,4:3}};
const V48_METAMAGIC={careful:'Careful Spell',distant:'Distant Spell',empowered:'Empowered Spell',extended:'Extended Spell',heightened:'Heightened Spell',quickened:'Quickened Spell',subtle:'Subtle Spell',twinned:'Twinned Spell'};
const V48_INVOCATIONS={armorShadows:'Armor of Shadows',devilsSight:"Devil's Sight",eldritchSight:'Eldritch Sight',fiendishVigor:'Fiendish Vigor',maskManyFaces:'Mask of Many Faces',agonizingBlast:'Agonizing Blast',repellingBlast:'Repelling Blast',thiefFiveFates:'Thief of Five Fates'};
const V48_PACT_BOONS={chain:'Pact of the Chain',blade:'Pact of the Blade',tome:'Pact of the Tome'};
SPELLS_KNOWN.bard={...V48_KNOWN.bard};SPELLS_KNOWN.sorcerer={...V48_KNOWN.sorcerer};SPELLS_KNOWN.warlock={...V48_KNOWN.warlock};

function v48AddClass(spellId,classId){const sp=SPELLS[spellId];if(sp&&!sp.classes.includes(classId))sp.classes.push(classId);}
function v48Spell(def){if(!SPELLS[def.id])SPELLS[def.id]=def;else for(const c of def.classes||[])v48AddClass(def.id,c);}
[
 {id:'shatter',name:'Shatter',classes:['bard','sorcerer','warlock'],level:2,school:'Evocation',castingTime:'1 action',range:'60 ft',duration:'Instantaneous',components:'V, S, M',save:'con',damage:{dice:'3d8',type:'thunder',upcast:{dicePerLevel:'1d8'}},summary:'A burst of sound damages creatures in an area; Constitution save for reduced damage.'},
 {id:'invisibility',name:'Invisibility',classes:['bard','sorcerer','warlock','wizard'],level:2,school:'Illusion',castingTime:'1 action',range:'Touch',duration:'Concentration, up to 1 hour',components:'V, S, M',concentration:true,summary:'A touched creature becomes invisible until the effect ends.'},
 {id:'hold-person',name:'Hold Person',classes:['bard','cleric','druid','sorcerer','warlock','wizard'],level:2,school:'Enchantment',castingTime:'1 action',range:'60 ft',duration:'Concentration, up to 1 minute',components:'V, S, M',concentration:true,save:'wis',summary:'A humanoid that fails its Wisdom save is paralyzed while the spell lasts.'},
 {id:'heat-metal',name:'Heat Metal',classes:['bard','druid'],level:2,school:'Transmutation',castingTime:'1 action',range:'60 ft',duration:'Concentration, up to 1 minute',components:'V, S, M',concentration:true,damage:{dice:'2d8',type:'fire',upcast:{dicePerLevel:'1d8'}},summary:'Heats a manufactured metal object and can deal repeated fire damage.'},
 {id:'moonbeam',name:'Moonbeam',classes:['druid'],level:2,school:'Evocation',castingTime:'1 action',range:'120 ft',duration:'Concentration, up to 1 minute',components:'V, S, M',concentration:true,save:'con',damage:{dice:'2d10',type:'radiant',upcast:{dicePerLevel:'1d10'}},summary:'A cylinder of light damages creatures that enter or start there.'},
 {id:'barkskin',name:'Barkskin',classes:['druid'],level:2,school:'Transmutation',castingTime:'1 action',range:'Touch',duration:'Concentration, up to 1 hour',components:'V, S, M',concentration:true,summary:'Protective magic prevents the target AC from being lower than 16.'},
 {id:'mirror-image',name:'Mirror Image',classes:['sorcerer','warlock','wizard'],level:2,school:'Illusion',castingTime:'1 action',range:'Self',duration:'1 minute',components:'V, S',summary:'Illusory duplicates make attacks against you more likely to miss; attack redirection remains table-managed.'},
 {id:'scorching-ray',name:'Scorching Ray',classes:['sorcerer','wizard'],level:2,school:'Evocation',castingTime:'1 action',range:'120 ft',duration:'Instantaneous',components:'V, S',damage:{dice:'2d6',type:'fire'},summary:'Creates multiple fire rays; roll each spell attack separately.'},
 {id:'misty-step',name:'Misty Step',classes:['sorcerer','warlock','wizard'],level:2,school:'Conjuration',castingTime:'1 bonus action',range:'Self',duration:'Instantaneous',components:'V',summary:'Teleport a short distance to an unoccupied space you can see.'},
 {id:'fireball',name:'Fireball',classes:['sorcerer','wizard'],level:3,school:'Evocation',castingTime:'1 action',range:'150 ft',duration:'Instantaneous',components:'V, S, M',save:'dex',damage:{dice:'8d6',type:'fire',upcast:{dicePerLevel:'1d6'}},summary:'A fiery explosion damages creatures in a large area; Dexterity save for reduced damage.'},
 {id:'counterspell',name:'Counterspell',classes:['sorcerer','warlock','wizard'],level:3,school:'Abjuration',castingTime:'1 reaction',range:'60 ft',duration:'Instantaneous',components:'S',summary:'Interrupts another creature spell; higher-level resolution may require an ability check.'},
 {id:'fly',name:'Fly',classes:['sorcerer','warlock','wizard'],level:3,school:'Transmutation',castingTime:'1 action',range:'Touch',duration:'Concentration, up to 10 minutes',components:'V, S, M',concentration:true,summary:'Grants a flying speed while concentration lasts.'},
 {id:'hypnotic-pattern',name:'Hypnotic Pattern',classes:['bard','sorcerer','warlock','wizard'],level:3,school:'Illusion',castingTime:'1 action',range:'120 ft',duration:'Concentration, up to 1 minute',components:'S, M',concentration:true,save:'wis',summary:'A visual pattern can charm and incapacitate creatures that fail Wisdom saves.'},
 {id:'dispel-magic',name:'Dispel Magic',classes:['bard','cleric','druid','sorcerer','warlock','wizard'],level:3,school:'Abjuration',castingTime:'1 action',range:'120 ft',duration:'Instantaneous',components:'V, S',summary:'Ends spells on a target; higher-level spells can require an ability check.'},
 {id:'call-lightning',name:'Call Lightning',classes:['druid'],level:3,school:'Conjuration',castingTime:'1 action',range:'120 ft',duration:'Concentration, up to 10 minutes',components:'V, S',concentration:true,save:'dex',damage:{dice:'3d10',type:'lightning',upcast:{dicePerLevel:'1d10'}},summary:'Calls repeated lightning bolts while concentration lasts.'},
 {id:'plant-growth',name:'Plant Growth',classes:['bard','druid'],level:3,school:'Transmutation',castingTime:'1 action',range:'150 ft',duration:'Instantaneous',components:'V, S',summary:'Vegetation becomes extremely thick in the affected area; terrain handling remains manual.'},
 {id:'hunger-of-hadar',name:'Hunger of Hadar',classes:['warlock'],level:3,school:'Conjuration',castingTime:'1 action',range:'150 ft',duration:'Concentration, up to 1 minute',components:'V, S, M',concentration:true,summary:'Creates a dangerous dark area that can deal cold and acid damage; area tracking remains manual.'}
].forEach(v48Spell);


[
 {id:'water-breathing',name:'Water Breathing',classes:['druid','sorcerer','wizard'],level:3,school:'Transmutation',castingTime:'1 action',range:'30 ft',duration:'24 hours',components:'V, S, M',ritual:true,summary:'Up to ten willing creatures can breathe underwater for the duration.'},
 {id:'water-walk',name:'Water Walk',classes:['cleric','druid','ranger','sorcerer'],level:3,school:'Transmutation',castingTime:'1 action',range:'30 ft',duration:'1 hour',components:'V, S, M',ritual:true,summary:'Willing creatures can move across liquid surfaces as if they were solid ground.'},
 {id:'vicious-mockery',name:'Vicious Mockery',classes:['bard'],level:0,school:'Enchantment',castingTime:'1 action',range:'60 ft',duration:'Instantaneous',components:'V',save:'wis',damage:{dice:'1d4',type:'psychic'},summary:'A target that fails its Wisdom save takes psychic damage and has disadvantage on its next qualifying attack.'},
 {id:'produce-flame',name:'Produce Flame',classes:['druid'],level:0,school:'Conjuration',castingTime:'1 action',range:'Self',duration:'10 minutes',components:'V, S',damage:{dice:'1d8',type:'fire'},summary:'Create a flame for light or hurl it as a ranged spell attack.'},
 {id:'shillelagh',name:'Shillelagh',classes:['druid'],level:0,school:'Transmutation',castingTime:'1 bonus action',range:'Touch',duration:'1 minute',components:'V, S, M',summary:'Empowers a club or quarterstaff; weapon-state automation remains manual.'},
 {id:'eldritch-blast',name:'Eldritch Blast',classes:['warlock'],level:0,school:'Evocation',castingTime:'1 action',range:'120 ft',duration:'Instantaneous',components:'V, S',damage:{dice:'1d10',type:'force'},summary:'A ranged spell attack that deals force damage.'}
].forEach(v48Spell);

['vicious-mockery','minor-illusion','mage-hand','prestidigitation'].forEach(id=>v48AddClass(id,'bard'));
['guidance','produce-flame','resistance','shillelagh'].forEach(id=>v48AddClass(id,'druid'));
['fire-bolt','ray-of-frost','mage-hand','minor-illusion','prestidigitation'].forEach(id=>v48AddClass(id,'sorcerer'));
['eldritch-blast','mage-hand','minor-illusion','prestidigitation'].forEach(id=>v48AddClass(id,'warlock'));

function v48MaxSpellLevel(target){return target>=5?3:target>=3?2:1;}
function v48KnownTarget(id,target){return V48_KNOWN[id]?.[target]||0;}
function v48CantripTarget(id,target){const table=V48_CANTRIPS[id]||{};let n=0;for(const [lvl,count] of Object.entries(table))if(target>=Number(lvl))n=Math.max(n,count);return n;}
function v48SpellPool(id,target){return spellsForClass(id).filter(s=>s.level>0&&s.level<=v48MaxSpellLevel(target));}
function v48CantripPool(id){return spellsForClass(id).filter(s=>s.level===0);}
function v48KnownPlan(c,id,target,{newSpells=[],replaceOldSpell=null,replaceNewSpell=null}={}){
 let base=[...knownSpellIds(c)],errors=[];const allowed=new Set(v48SpellPool(id,target).map(s=>s.id));
 if(replaceOldSpell||replaceNewSpell){if(!replaceOldSpell||!replaceNewSpell)errors.push('Choose both spells for replacement.');else if(!base.includes(replaceOldSpell))errors.push('The spell to replace is not known.');else if(!allowed.has(replaceNewSpell))errors.push('The replacement spell is not available at this level.');else if(base.includes(replaceNewSpell)&&replaceNewSpell!==replaceOldSpell)errors.push('The replacement spell is already known.');else base=base.map(x=>x===replaceOldSpell?replaceNewSpell:x);}
 base=[...new Set(base)];const targetCount=v48KnownTarget(id,target),need=Math.max(0,targetCount-base.length),adds=[...new Set(newSpells.filter(Boolean))];
 if(adds.length!==need)errors.push(`Choose exactly ${need} new ${CLASS_INFO[id].name} spell${need===1?'':'s'}.`);
 if(adds.some(x=>!allowed.has(x)||base.includes(x)))errors.push('One or more new spells are invalid or already known.');
 const final=[...new Set([...base,...adds])];if(final.length!==targetCount)errors.push(`${CLASS_INFO[id].name} ${target} should know ${targetCount} leveled spells.`);
 return{ok:!errors.length,errors,final,added:adds,replaced:replaceOldSpell&&replaceNewSpell&&replaceOldSpell!==replaceNewSpell?{from:replaceOldSpell,to:replaceNewSpell}:null};
}
function v48CantripPlan(c,id,target,{newCantrips=[]}={}){
 const s=ensureSpellcasting(c),base=[...new Set(s.cantrips||[])],targetCount=v48CantripTarget(id,target),need=Math.max(0,targetCount-base.length),allowed=new Set(v48CantripPool(id).map(x=>x.id)),adds=[...new Set(newCantrips.filter(Boolean))],errors=[];
 if(adds.length!==need)errors.push(`Choose exactly ${need} new cantrip${need===1?'':'s'}.`);if(adds.some(x=>!allowed.has(x)||base.includes(x)))errors.push('One or more selected cantrips are invalid or already known.');
 return{ok:!errors.length,errors,final:[...new Set([...base,...adds])],added:adds};
}

const v47SlotMaximums_48=slotMaximums;
slotMaximums=function(c){const id=primaryClassId(c),lvl=Math.min(5,Math.max(1,casterClassLevel(c,id)));if(['bard','druid','sorcerer'].includes(id))return{...(V48_FULL_SLOTS[lvl]||{})};if(id==='warlock')return{...(V48_WARLOCK_SLOTS[lvl]||{})};return v47SlotMaximums_48(c);};

const v47AlwaysPrepared_48=alwaysPreparedSpells;
alwaysPreparedSpells=function(c){const out=[...v47AlwaysPrepared_48(c)];if(primaryClassId(c)==='druid'&&primaryClass(c)?.subclassId==='land-coast'){const lvl=v46ClassLevel(c,'druid');if(lvl>=3)out.push('mirror-image','misty-step');if(lvl>=5){v48AddClass('water-breathing','druid');v48AddClass('water-walk','druid');out.push('water-breathing','water-walk');}}return[...new Set(out.filter(id=>SPELLS[id]))];};

function v48Resource(c,id,name,max,recovery){let r=c.resources.find(x=>x.id===id);if(!r){r={id,name,current:max,maximum:max,recovery:[...recovery]};c.resources.push(r);}else{const old=Number(r.maximum||0);r.maximum=max;r.current=Math.min(max,Number(r.current||0)+Math.max(0,max-old));r.recovery=[...recovery];}return r;}
function v48SyncResources(c){
 const id=primaryClassId(c),lvl=v46ClassLevel(c,id);
 if(id==='bard'){const max=Math.max(1,getAbilityModifier(c,'cha'));const r=v48Resource(c,'bardic-inspiration','Bardic Inspiration',max,lvl>=5?['shortRest','longRest']:['longRest']);r.die=lvl>=5?'d8':'d6';}
 if(id==='druid'&&lvl>=2){v48Resource(c,'wild-shape','Wild Shape',2,['shortRest','longRest']);v48Resource(c,'natural-recovery','Natural Recovery',1,['longRest']);}
 if(id==='sorcerer'&&lvl>=2)v48Resource(c,'sorcery-points','Sorcery Points',lvl,['longRest']);
}
const v47MigrateCharacter_48=migrateCharacter;
migrateCharacter=function(c){const out=v47MigrateCharacter_48(c),id=primaryClassId(c);if(['bard','druid','sorcerer','warlock'].includes(id)){ensureSpellcasting(c);v48SyncResources(c);}return out;};

function v48CasterLevelUp(character,{hpMode='fixed',hpRoll=null,asi={},newSpells=[],replaceOldSpell=null,replaceNewSpell=null,newCantrips=[],metamagic=[],invocations=[],pactBoon=null}={}){
 const c=character;migrateCharacter(c);const id=primaryClassId(c),info=CLASS_INFO[id],cls=c.progression.classes.find(x=>x.classId===id),oldLevel=Number(cls?.level||1),target=oldLevel+1,errors=[];
 if(!['bard','druid','sorcerer','warlock'].includes(id))return{ok:false,errors:['Unsupported v4.8 class.']};if(oldLevel>=5)return{ok:false,errors:['Core v4.8 supports this class through level 5.']};if(target===4)errors.push(...validateASI(c,asi));
 let knownPlan=null;if(['bard','sorcerer','warlock'].includes(id)){knownPlan=v48KnownPlan(c,id,target,{newSpells,replaceOldSpell,replaceNewSpell});if(!knownPlan.ok)errors.push(...knownPlan.errors);}
 const cantripPlan=v48CantripPlan(c,id,target,{newCantrips});if(!cantripPlan.ok)errors.push(...cantripPlan.errors);
 if(id==='sorcerer'&&target===3){const m=[...new Set(metamagic.filter(x=>V48_METAMAGIC[x]))];if(m.length!==2)errors.push('Choose exactly two Metamagic options.');}
 if(id==='warlock'&&target===2){const inv=[...new Set(invocations.filter(x=>V48_INVOCATIONS[x]))];if(inv.length!==2)errors.push('Choose exactly two Eldritch Invocations.');}
 if(id==='warlock'&&target===3&&!V48_PACT_BOONS[pactBoon])errors.push('Choose a Pact Boon.');if(id==='warlock'&&target===5){const inv=[...new Set(invocations.filter(x=>V48_INVOCATIONS[x]))];if(inv.length!==1)errors.push('Choose one additional Eldritch Invocation.');}
 if(errors.length)return{ok:false,errors};
 const oldMax=maxHP(c),wasFull=c.health.currentHP>=oldMax,oldCon=getAbilityModifier(c,'con');let dieValue=info.fixedHP;if(hpMode==='roll')dieValue=Math.max(1,Math.min(Number(info.hitDie.slice(1)),Number(hpRoll)||1));
 cls.level=target;c.health.maxHPBase=oldMax+Math.max(1,dieValue+oldCon);c.health.hitDice[info.hitDie]||={maximum:oldLevel,remaining:oldLevel};const hd=c.health.hitDice[info.hitDie];hd.maximum=target;hd.remaining=Math.min(hd.maximum,Number(hd.remaining||0)+1);const changes=[`${info.name} ${oldLevel} -> ${target}`,`Max HP ${oldMax} -> ${c.health.maxHPBase}`];
 const sc=ensureSpellcasting(c);sc.cantrips=[...cantripPlan.final];if(cantripPlan.added.length)changes.push(`New cantrip: ${cantripPlan.added.map(x=>getSpell(x)?.name||x).join(', ')}`);
 if(knownPlan){sc.spellsKnown=[...knownPlan.final];sc.prepared=[...sc.spellsKnown];if(knownPlan.added.length)changes.push(`Learned: ${knownPlan.added.map(x=>getSpell(x)?.name||x).join(', ')}`);if(knownPlan.replaced)changes.push(`Replaced ${getSpell(knownPlan.replaced.from)?.name||knownPlan.replaced.from} -> ${getSpell(knownPlan.replaced.to)?.name||knownPlan.replaced.to}`);}
 c.progression.classChoices||={};
 if(id==='bard'){if(target===2)changes.push('New Features: Jack of All Trades, Song of Rest d6');if(target===3){cls.subclassId='lore';changes.push('Bard College: College of Lore','New Features: Expertise, Bonus Proficiencies, Cutting Words','2nd-level spell slots');}if(target===4)applyASI(c,asi,target,oldCon,changes);if(target===5){c.progression.classChoices.bardicDie='d8';changes.push('Bardic Inspiration die becomes d8','New Feature: Font of Inspiration','3rd-level spell slots');}}
 if(id==='druid'){if(target===2){cls.subclassId='land-coast';c.progression.classChoices.landType='coast';changes.push('Druid Circle: Circle of the Land (Coast)','New Features: Wild Shape, Natural Recovery','Bonus Druid cantrip');}if(target===3)changes.push('2nd-level spell slots','Circle Spells become available');if(target===4){applyASI(c,asi,target,oldCon,changes);c.progression.classChoices.wildShapeCR='1/2';changes.push('Wild Shape improves to CR 1/2 forms without flying speed');}if(target===5)changes.push('3rd-level spell slots','Additional Circle Spells');}
 if(id==='sorcerer'){if(target===2)changes.push('New Feature: Font of Magic','Sorcery Points: 2');if(target===3){c.progression.classChoices.metamagic=[...new Set(metamagic)];changes.push(`Metamagic: ${c.progression.classChoices.metamagic.map(x=>V48_METAMAGIC[x]).join(', ')}`,'2nd-level spell slots');}if(target===4)applyASI(c,asi,target,oldCon,changes);if(target===5)changes.push('Sorcery Points: 5','3rd-level spell slots');}
 if(id==='warlock'){c.progression.classChoices.invocations||=[];if(target===2){c.progression.classChoices.invocations=[...new Set(invocations)];changes.push(`Eldritch Invocations: ${c.progression.classChoices.invocations.map(x=>V48_INVOCATIONS[x]).join(', ')}`,'Pact slots: 2');}if(target===3){c.progression.classChoices.pactBoon=pactBoon;changes.push(`Pact Boon: ${V48_PACT_BOONS[pactBoon]}`,'Pact slots become 2nd level');}if(target===4)applyASI(c,asi,target,oldCon,changes);if(target===5){c.progression.classChoices.invocations=[...new Set([...c.progression.classChoices.invocations,...invocations])];changes.push(`New Invocation: ${invocations.map(x=>V48_INVOCATIONS[x]).join(', ')}`,'Pact slots become 3rd level');}}
 v48SyncResources(c);if(wasFull)c.health.currentHP=c.health.maxHPBase;else c.health.currentHP=Math.min(c.health.currentHP,c.health.maxHPBase);return{ok:true,oldLevel,target,oldMax,newMax:c.health.maxHPBase,changes};
}
const v47LevelUpCharacter_48=levelUpCharacter;
levelUpCharacter=function(c,options={}){return['bard','druid','sorcerer','warlock'].includes(primaryClassId(c))?v48CasterLevelUp(c,options):v47LevelUpCharacter_48(c,options);};

const v47FeatureList_48=featureList;
featureList=function(c){let html=v47FeatureList_48(c),ci=classInfo(c);
 if(ci.id==='bard'){if(ci.level>=2)html+=`<div class="skillrow"><span><strong>Jack of All Trades</strong><br><small class="muted">Adds half proficiency to eligible ability checks; contextual application is shown as a class feature.</small></span><span class="pill">Passive</span></div><div class="skillrow"><span><strong>Song of Rest</strong><br><small class="muted">d6 extra healing during qualifying Short Rests; party healing remains manual.</small></span><span class="pill">Rest</span></div>`;if(ci.level>=3)html+=`<div class="skillrow"><span><strong>College of Lore</strong><br><small class="muted">Expertise, Bonus Proficiencies and Cutting Words are available.</small></span><span class="pill">Subclass</span></div>`;if(ci.level>=5)html+=`<div class="skillrow"><span><strong>Font of Inspiration</strong><br><small class="muted">Bardic Inspiration is d8 and now refreshes on Short or Long Rest; automated in the resource tracker.</small></span><span class="pill">Resource</span></div>`;}
 if(ci.id==='druid'){if(ci.level>=2)html+=`<div class="skillrow"><span><strong>Wild Shape</strong><br><small class="muted">2 uses per Short/Long Rest. Form selection and replacement of physical statistics remain table-managed in this build.</small></span><span class="pill">Resource</span></div><div class="skillrow"><span><strong>Circle of the Land: Coast</strong><br><small class="muted">Natural Recovery and a bonus cantrip. Circle spells are always prepared as they become available.</small></span><span class="pill">Subclass</span></div>`;if(ci.level>=4)html+=`<div class="skillrow"><span><strong>Wild Shape Improvement</strong><br><small class="muted">CR up to 1/2, still without flying speed.</small></span><span class="pill">Passive</span></div>`;}
 if(ci.id==='sorcerer'){if(ci.level>=2)html+=`<div class="skillrow"><span><strong>Font of Magic</strong><br><small class="muted">${ci.level} Sorcery Points, restored on Long Rest. Flexible Casting conversion remains manual.</small></span><span class="pill">Resource</span></div>`;if(ci.level>=3)html+=`<div class="skillrow"><span><strong>Metamagic</strong><br><small class="muted">${(c.progression?.classChoices?.metamagic||[]).map(x=>esc(V48_METAMAGIC[x]||x)).join(', ')||'-'}</small></span><span class="pill">Class</span></div>`;}
 if(ci.id==='warlock'){if(ci.level>=2)html+=`<div class="skillrow"><span><strong>Eldritch Invocations</strong><br><small class="muted">${(c.progression?.classChoices?.invocations||[]).map(x=>esc(V48_INVOCATIONS[x]||x)).join(', ')||'-'}</small></span><span class="pill">Class</span></div>`;if(ci.level>=3)html+=`<div class="skillrow"><span><strong>Pact Boon</strong><br><small class="muted">${esc(V48_PACT_BOONS[c.progression?.classChoices?.pactBoon]||'-')}</small></span><span class="pill">Class</span></div>`;html+=`<div class="skillrow"><span><strong>Pact Magic</strong><br><small class="muted">Pact slots scale with Warlock level and refresh on a Short or Long Rest.</small></span><span class="pill">Magic</span></div>`;}
 return html;};

function v48CanLevel(ci){return ci.level<5&&['bard','druid','sorcerer','warlock'].includes(ci.id);}
const v47SheetScreen_48=sheetScreen;
sheetScreen=function(){let html=v47SheetScreen_48(),ci=classInfo(state.active);if(v48CanLevel(ci)&&!html.includes('data-act="level-up"'))html=html.replace('<button data-breakdown="ac" class="compact">AC</button>',`<button data-breakdown="ac" class="compact">AC</button><button class="compact primary" data-act="level-up">LEVEL UP</button>`);return html;};
const v47MoreScreen_48=moreScreen;
moreScreen=function(){let html=v47MoreScreen_48(),ci=classInfo(state.active);if(v48CanLevel(ci)&&!html.includes('data-act="level-up"'))html=html.replace('<button class="wide" style="margin-top:8px" data-act="dice">',`<button class="primary wide" data-act="level-up">LEVEL UP</button><button class="wide" style="margin-top:8px" data-act="dice">`);return html.replace(/Core v4\.7/g,'Core v4.8');};

function v48Options(id,label,items){return `<label>${label}</label><select id="${id}">${items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select>`;}
function v48LevelSpellUI(c,id,target){
 const sc=ensureSpellcasting(c);let html='';if(['bard','sorcerer','warlock'].includes(id)){const pool=v48SpellPool(id,target),existing=knownSpellIds(c),need=Math.max(0,v48KnownTarget(id,target)-existing.length);for(let i=0;i<need;i++)html+=v48Options(`m-v48-spell-${i}`,`New ${CLASS_INFO[id].name} spell ${i+1}`,pool.map(s=>({id:s.id,name:`${s.name} (L${s.level})`})));if(existing.length){html+=v48Options('m-v48-replace-old','Optional: replace known spell',[{id:'',name:'No replacement'},...existing.map(x=>({id:x,name:getSpell(x)?.name||x}))]);html+=v48Options('m-v48-replace-new','Replacement spell',[{id:'',name:'-'},...pool.map(s=>({id:s.id,name:`${s.name} (L${s.level})`}))]);}}
 const canNeed=Math.max(0,v48CantripTarget(id,target)-(sc.cantrips||[]).length),canPool=v48CantripPool(id).filter(x=>!(sc.cantrips||[]).includes(x.id));for(let i=0;i<canNeed;i++)html+=v48Options(`m-v48-cantrip-${i}`,`New cantrip ${i+1}`,canPool.map(s=>({id:s.id,name:s.name})));return html;
}
const v47RenderModal_48=renderModal;
renderModal=function(){const m=state.modal,c=state.active,ci=c?classInfo(c):null;if(m?.type==='levelUp'&&ci&&v48CanLevel(ci)){
 const target=ci.level+1,info=CLASS_INFO[ci.id],spells=v48LevelSpellUI(c,ci.id,target),asi=target===4?`<label>ASI first +1</label><select id="m-asi-1">${ABILITIES.map(a=>`<option value="${a}">${a.toUpperCase()} (${effectiveAbilityScore(c,a)})</option>`).join('')}</select><label>ASI second +1</label><select id="m-asi-2">${ABILITIES.map(a=>`<option value="${a}">${a.toUpperCase()} (${effectiveAbilityScore(c,a)})</option>`).join('')}</select>`:'';
 let special='';if(ci.id==='sorcerer'&&target===3)special=`<label>Metamagic option 1</label><select id="m-v48-meta-1">${Object.entries(V48_METAMAGIC).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select><label>Metamagic option 2</label><select id="m-v48-meta-2">${Object.entries(V48_METAMAGIC).map(([id,name],i)=>`<option value="${id}" ${i===1?'selected':''}>${name}</option>`).join('')}</select>`;
 if(ci.id==='warlock'&&target===2)special=`<label>Invocation 1</label><select id="m-v48-inv-1">${Object.entries(V48_INVOCATIONS).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select><label>Invocation 2</label><select id="m-v48-inv-2">${Object.entries(V48_INVOCATIONS).map(([id,name],i)=>`<option value="${id}" ${i===1?'selected':''}>${name}</option>`).join('')}</select>`;
 if(ci.id==='warlock'&&target===3)special=v48Options('m-v48-boon','Pact Boon',Object.entries(V48_PACT_BOONS).map(([id,name])=>({id,name})));
 if(ci.id==='warlock'&&target===5){const have=new Set(c.progression?.classChoices?.invocations||[]),choices=Object.entries(V48_INVOCATIONS).filter(([id])=>!have.has(id)).map(([id,name])=>({id,name}));special=v48Options('m-v48-inv-1','New Eldritch Invocation',choices);}
 const body=`<h2>Level Up: ${esc(ci.name)} ${ci.level} -> ${target}</h2><label>HP increase</label><select id="m-hp-mode"><option value="fixed">Fixed: ${info.fixedHP} + CON modifier</option><option value="roll">Roll 1${info.hitDie} + CON modifier</option></select>${special}${spells}${asi}<div id="level-errors" class="error">${(m.errors||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div><button class="primary wide" data-modal-act="apply-level-up">LEVEL UP</button>`;return `<div class="modalback" data-modal-act="backdrop"><div class="modal" role="dialog"><div class="between row"><span></span><button class="compact ghost" data-modal-act="close">Close</button></div>${body}</div></div>`;
 }return v47RenderModal_48();};
const v47ApplyLevelUpFromModal_48=applyLevelUpFromModal;
applyLevelUpFromModal=async function(){const c=state.active,ci=classInfo(c);if(!v48CanLevel(ci))return v47ApplyLevelUpFromModal_48();const target=ci.level+1,info=CLASS_INFO[ci.id],hpMode=document.querySelector('#m-hp-mode').value,hpRoll=hpMode==='roll'?rollDie(Number(info.hitDie.slice(1))):null,options={hpMode,hpRoll,asi:{},newSpells:[],newCantrips:[],replaceOldSpell:document.querySelector('#m-v48-replace-old')?.value||null,replaceNewSpell:document.querySelector('#m-v48-replace-new')?.value||null,metamagic:[],invocations:[],pactBoon:document.querySelector('#m-v48-boon')?.value||null};document.querySelectorAll('[id^="m-v48-spell-"]').forEach(x=>options.newSpells.push(x.value));document.querySelectorAll('[id^="m-v48-cantrip-"]').forEach(x=>options.newCantrips.push(x.value));document.querySelectorAll('[id^="m-v48-meta-"]').forEach(x=>options.metamagic.push(x.value));document.querySelectorAll('[id^="m-v48-inv-"]').forEach(x=>options.invocations.push(x.value));if(target===4){const a1=document.querySelector('#m-asi-1').value,a2=document.querySelector('#m-asi-2').value;options.asi[a1]=(options.asi[a1]||0)+1;options.asi[a2]=(options.asi[a2]||0)+1;}const preview=levelUpCharacter(deep(c),options);if(!preview.ok){state.modal.errors=preview.errors;render();return;}pushUndo(c,'Level Up');const result=levelUpCharacter(c,options);addLog(c,'Level Up',result.changes.join(' | '));await persist();state.modal={type:'levelSummary',changes:result.changes};render();};
