'use strict';
DND.Content=(()=>{let packs=[];const abilities=['str','dex','con','int','wis','cha'];
const ru={barbarian:'Варвар',bard:'Бард',cleric:'Жрец',druid:'Друид',fighter:'Воин',monk:'Монах',paladin:'Паладин',ranger:'Следопыт',rogue:'Плут',sorcerer:'Чародей',warlock:'Колдун',wizard:'Волшебник',human:'Человек',elf:'Эльф',dwarf:'Дварф',halfling:'Полурослик',gnome:'Гном','half-elf':'Полуэльф','half-orc':'Полуорк',dragonborn:'Драконорождённый',tiefling:'Тифлинг',acolyte:'Прислужник','hill-dwarf':'Холмовой дварф','high-elf':'Высший эльф','lightfoot-halfling':'Легконогий полурослик','rock-gnome':'Скальный гном',acrobatics:'Акробатика','animal-handling':'Уход за животными',arcana:'Магия',athletics:'Атлетика',deception:'Обман',history:'История',insight:'Проницательность',intimidation:'Запугивание',investigation:'Анализ',medicine:'Медицина',nature:'Природа',perception:'Внимательность',performance:'Выступление',persuasion:'Убеждение',religion:'Религия','sleight-of-hand':'Ловкость рук',stealth:'Скрытность',survival:'Выживание',blinded:'Ослеплён',charmed:'Очарован',deafened:'Оглох',frightened:'Испуган',grappled:'Схвачен',incapacitated:'Недееспособен',invisible:'Невидим',paralyzed:'Парализован',petrified:'Окаменел',poisoned:'Отравлен',prone:'Лежит',restrained:'Опутан',stunned:'Ошеломлён',unconscious:'Без сознания',exhaustion:'Истощение',acid:'Кислота',bludgeoning:'Дробящий',cold:'Холод',fire:'Огонь',force:'Силовой',lightning:'Молния',necrotic:'Некротический',piercing:'Колющий',poison:'Яд',psychic:'Психический',radiant:'Излучение',slashing:'Рубящий',thunder:'Звук'};
const help=[
['ac','Класс доспеха / AC','Без брони: 10 + DEX. Броня задаёт свою формулу, щит обычно +2. Альтернативные формулы не складываются.','armor-class'],
['concentration','Концентрация','Одно заклинание одновременно. После каждого источника урона: CON Save, DC max(10, floor(урон/2)). Урон по временным HP тоже учитывается. Недееспособность или смерть заканчивают концентрацию.','casting-a-spell'],
['death','0 HP и спасброски смерти','d20: 1 — два провала; 20 — восстановить 1 HP; 10+ — успех. Три успеха стабилизируют, три провала убивают. Урон при 0 HP даёт провал (крит — два). Остаток урона ≥ максимуму HP: мгновенная смерть.','damage-and-healing'],
['rest','Отдых','Короткий: не менее часа; Hit Dice + CON, минимум 0 лечения. Длительный: 8 часов, начало с 1+ HP, польза не чаще раза за 24 часа. Восстановить HP, ячейки и до половины всех Hit Dice, минимум 1. При еде и воде истощение −1.','resting'],
['advantage','Преимущество и помеха','Лучшее или худшее из 2d20. Любое количество источников преимущества и помехи взаимно отменяется до обычного броска. Натуральные 1 и 20 автоматически решают атаки, но не обычные проверки.','advantage-and-disadvantage'],
['cover','Укрытие / cover','Половинное укрытие: +2 AC и DEX Save; три четверти: +5. Полное укрытие препятствует прямому выбору цели. Обстоятельства определяет мастер.','cover'],
['falling','Падение / falling','1d6 дробящего за каждые 10 футов, максимум 20d6. Приземление лёжа, если урон не предотвращён.','the-environment'],
['hands','Две руки / two-handed','Two-handed требует обеих рук при атаке; Versatile меняет кубик в двух руках. Вторая атака лёгким оружием тратит бонусное действие; положительный модификатор к урону обычно не добавляется.','making-an-attack'],
['opportunity','Провоцированная атака / Opportunity Attack','Одна рукопашная атака реакцией, когда видимый враг выходит из досягаемости. Disengage предотвращает её. Расстояния и видимость задаёт игрок.','melee-attacks'],
['multiclass','Мультикласс','Требования проверяются для текущих и нового классов. Спасброски — от первого класса. Заклинания определяются по каждому классу; ячейки полных и половинных заклинателей объединяются, Pact Magic отдельно. Extra Attack не складывается.','multiclassing'],
['level-up','Повышение уровня','HP и Hit Die добавляются каждый уровень. CON применяется ко всем уровням. Мастерство зависит от общего уровня; ASI и особенности — от уровня класса.','beyond-1st-level'],
['exhaustion','Истощение 2014','1: помеха проверкам; 2: скорость вдвое; 3: помеха атакам и спасброскам; 4: максимум HP вдвое; 5: скорость 0; 6: смерть. Эффекты накапливаются.','conditions'],
['passive','Пассивные проверки','10 + бонус проверки. Преимущество +5, помеха −5. Для восприятия важны условия видимости и слышимости.','ability-checks'],
['actions','Действия в бою','Перемещение и действие в ход. Бонусное действие — при наличии умения. Реакция — одна до начала следующего хода. Attack, Cast, Dash, Disengage, Dodge, Help, Hide, Ready, Search, Use an Object доступны при соблюдении условий.','actions-in-combat'],
['slots','Заклинания и ячейки','Ячейка не ниже уровня заклинания. Заговоры ячеек не требуют. После заклинания бонусным действием в этот ход можно произносить лишь заговор со временем 1 действие.','casting-a-spell'],
['inspiration','Вдохновение','Даётся мастером. Расходуется на преимущество одной атаки, проверки или спасброска. Не накапливается.','inspiration']
].map(([id,name,quick,section])=>({index:'help-'+id,name,quick,desc:[quick],section}));
function list(type){return [...(globalThis.SRD?.[type]||[]),...(type==='rule-sections'?help:[]),...packs.filter(p=>p.enabled!==false).flatMap(p=>(p.content?.[type]||[]).map(x=>({...x,homebrew:true,pack:p.id})))];}
const get=(t,id)=>list(t).find(x=>x.index===id),name=(t,id)=>ru[id]||get(t,id)?.name||id,label=x=>ru[x.index]?ru[x.index]+' · '+x.name:x.name;
const level=(id,l)=>get('levels',id+'-'+l)||{};
function category(id){return list('equipment').filter(x=>id==='simple-weapons'?x.weapon_category==='Simple':id==='martial-weapons'?x.weapon_category==='Martial':id.includes('-melee-weapons')?x.weapon_category?.toLowerCase()===id.split('-')[0]&&x.weapon_range==='Melee':id.includes('-ranged-weapons')?x.weapon_category?.toLowerCase()===id.split('-')[0]&&x.weapon_range==='Ranged':[x.equipment_category?.index,x.gear_category?.index].includes(id)||id==='musical-instruments'&&x.tool_category==='Musical Instrument');}
function equipmentOptions(set,choose=1){let out=[];if(set?.option_set_type==='equipment_category')out=category(set.equipment_category.index).map(x=>[{index:x.index,quantity:1}]);else for(const o of set?.options||[]){if(o.option_type==='counted_reference')out.push([{index:o.of.index,quantity:o.count}]);if(o.option_type==='choice')out.push(...equipmentOptions(o.choice.from,o.choice.choose));if(o.option_type==='multiple'){let rows=[[]];for(const i of o.items){const v=equipmentOptions({options:[i]});rows=rows.flatMap(a=>v.map(b=>[...a,...b]));}out.push(...rows);}}if(choose>1){let rows=[[]];for(let i=0;i<choose;i++)rows=rows.flatMap(a=>out.map(b=>[...a,...b]));out=rows;}return out;}
const equipmentChoices=id=>(get('classes',id)?.starting_equipment_options||[]).map(x=>({desc:x.desc||'Снаряжение',options:equipmentOptions(x.from,x.choose)}));
function validatePack(p){if(p?.schemaVersion!==1||typeof p.id!=='string'||!p.id.startsWith('custom-')||!p.name||!p.content)throw Error('Пакет: schemaVersion 1, id custom-…, name, content');const allowed=['races','subraces','classes','subclasses','backgrounds','feats','spells','equipment','features','resources','rule-sections','effects','levels','traits'];let n=0;for(const [t,items]of Object.entries(p.content)){if(!allowed.includes(t)||!Array.isArray(items))throw Error('Неизвестная категория '+t);for(const x of items){if(!x.index?.startsWith(p.id+'-')||!x.name)throw Error('У записи нужны index с префиксом пакета и name');if(t==='classes'&&![6,8,10,12].includes(x.hit_die))throw Error('Класс: hit_die 6,8,10,12');if(t==='spells'&&(!Number.isInteger(x.level)||x.level<0||x.level>9||!Array.isArray(x.classes)))throw Error('Заклинание: level 0–9 и classes');n++;}}if(n>3000)throw Error('Слишком большой пакет');return p;}
return {abilities,ru,help,list,get,name,label,level,equipmentChoices,validatePack,setPacks(p){packs=p||[]},skillAbility(id){return get('skills',id)?.ability_score?.index||'dex'}};})();
