'use strict';
DND.Effects=(()=>{const has=(c,id)=>c.conditions.includes(id);
function active(c){const result=[...c.effects];for(const i of c.inventory)if(i.equipped&&i.quantity>0&&(!i.requiresAttunement||i.attuned))for(const e of i.effects||[])result.push({...e,source:i.name});for(const id of c.feats||[])for(const e of DND.Content.get('feats',id)?.effects||[])result.push(e);return result.filter(e=>e.enabled!==false&&(e.remaining==null||e.remaining>0)&&(!e.concentration||c.concentration));}
const sum=(c,t)=>active(c).filter(e=>e.target===t&&(!e.operation||e.operation==='add')).reduce((s,e)=>s+(Number(e.value)||0),0);
function value(c,t,n){const set=active(c).filter(e=>e.target===t&&e.operation==='set');return (set.length?Math.max(...set.map(e=>+e.value)):n)+sum(c,t)}
function mode(c,kind,key='',ctx={}){const R=DND.Rules,advantage=[],disadvantage=[],add=(m,s)=>(m==='advantage'?advantage:disadvantage).push(s);if(['advantage','disadvantage'].includes(ctx.mode))add(ctx.mode,'Выбор игрока');if(ctx.inspiration)add('advantage','Вдохновение');if(has(c,'poisoned')&&['attack','check','skill'].includes(kind))add('disadvantage','Отравлен');if(has(c,'frightened')&&ctx.fearVisible&&['attack','check','skill'].includes(kind))add('disadvantage','Источник страха виден');if(c.exhaustion>=1&&['check','skill'].includes(kind))add('disadvantage','Истощение');if(c.exhaustion>=3&&['attack','save','death'].includes(kind))add('disadvantage','Истощение 3+');if(kind==='attack'){if(['blinded','prone','restrained'].some(x=>has(c,x)))add('disadvantage','Состояние');if(has(c,'invisible'))add('advantage','Невидимость');if(ctx.targetDisabled)add('advantage','Состояние цели');if(ctx.targetInvisible)add('disadvantage','Невидимая цель');if(ctx.targetProne)add(ctx.within5?'advantage':'disadvantage','Цель лежит');if(ctx.longRange||ctx.hostile5)add('disadvantage','Дальность / враг в 5 футах');if(ctx.heavySmall)add('disadvantage','Тяжёлое оружие / малый размер');}
if(kind==='save'&&key==='dex'&&has(c,'restrained'))add('disadvantage','Опутан');if(kind==='save'&&ctx.poison&&c.race==='dwarf')add('advantage','Устойчивость к яду');if(kind==='save'&&ctx.charm&&['elf','half-elf'].includes(c.race))add('advantage','Наследие фей');if(kind==='save'&&ctx.magic&&c.race==='gnome'&&['int','wis','cha'].includes(key))add('advantage','Хитрость гнома');if(kind==='save'&&key==='dex'&&R.classLevel(c,'barbarian')>=2&&ctx.visible&&!['blinded','deafened','incapacitated'].some(x=>has(c,x)))add('advantage','Чувство опасности');if(kind==='skill'&&key==='stealth'&&R.armor(c).body?.stealth_disadvantage)add('disadvantage','Броня');if(R.armor(c).untrained&&(kind==='attack'||['check','save'].includes(kind)&&['str','dex'].includes(key)||kind==='skill'&&['str','dex'].includes(DND.Content.skillAbility(key))))add('disadvantage','Нет владения бронёй');if(R.encumbrance(c).heavy&&(kind==='attack'||['save','check'].includes(kind)&&['str','dex','con'].includes(key)))add('disadvantage','Перегрузка');
for(const e of active(c))if(['advantage','disadvantage'].includes(e.operation)&&['all',kind,kind+'.'+key,...(ctx.concentration?['concentration']:[])].includes(e.target))add(e.operation,e.name||e.source||'Эффект');return {advantage,disadvantage,mode:advantage.length&&disadvantage.length?'normal':advantage.length?'advantage':disadvantage.length?'disadvantage':'normal',autoFail:kind==='save'&&['str','dex'].includes(key)&&['paralyzed','petrified','stunned','unconscious'].some(x=>has(c,x))||kind==='skill'&&key==='perception'&&(ctx.sight&&has(c,'blinded')||ctx.hearing&&has(c,'deafened'))};}
function tick(c,seconds){for(const e of c.effects)if(Number.isFinite(e.remaining)&&['rounds','minutes','hours'].includes(e.duration))e.remaining=Math.max(0,e.remaining-seconds);if(c.concentration?.remaining!=null){c.concentration.remaining=Math.max(0,c.concentration.remaining-seconds);if(!c.concentration.remaining)c.concentration=null;}}
return {has,active,sum,value,mode,tick,rest(c,type){c.effects=c.effects.filter(e=>!['rest',type,...(type==='long'?['short']:[])].includes(e.duration));}};})();
