'use strict';
DND.Rules=(()=>{const C=DND.Content,E=DND.Effects;const mod=n=>Math.floor((n-10)/2),level=c=>c.classes.reduce((n,x)=>n+x.level,0),classLevel=(c,id)=>c.classes.find(x=>x.id===id)?.level||0,prof=c=>2+Math.floor((level(c)-1)/4);
function score(c,a){let n=c.abilities[a]+(c.asi?.[a]||0);for(const x of [C.get('races',c.race),C.get('subraces',c.subrace)])for(const b of x?.ability_bonuses||[])if(b.ability_score.index===a)n+=b.bonus;n+=c.racialBonus?.[a]||0;if(classLevel(c,'barbarian')===20&&['str','con'].includes(a))n+=4;return E.value(c,'ability.'+a,n)}const ability=(c,a)=>mod(score(c,a));
function proficiencies(c){return [...new Set([...c.classes.flatMap((x,i)=>(i===0?C.get('classes',x.id)?.proficiencies:C.get('classes',x.id)?.multi_classing?.proficiencies)||[]).map(x=>x.index),...c.proficiencies,...(c.classes.some(x=>x.subclass==='life')?['heavy-armor']:[]),...(c.race==='dwarf'?['battleaxes','handaxes','light-hammers','warhammers']:[]),...(c.subrace==='high-elf'?['longswords','shortswords','shortbows','longbows']:[])])];}
function skillRank(c,id){return c.skills[id]||0}function skill(c,id){const rank=skillRank(c,id),a=C.skillAbility(id);return ability(c,a)+(rank?prof(c)*rank:classLevel(c,'bard')>=2?Math.floor(prof(c)/2):0)+E.sum(c,'skill.'+id)+E.sum(c,'check.'+a)}
const aura=c=>classLevel(c,'paladin')>=6&&!['unconscious','incapacitated','paralyzed','stunned'].some(x=>E.has(c,x))?Math.max(1,ability(c,'cha')):0;
const save=(c,a)=>ability(c,a)+(proficiencies(c).includes('saving-throw-'+a)||classLevel(c,'monk')>=14?prof(c):0)+aura(c)+E.sum(c,'save')+E.sum(c,'save.'+a);
const passive=(c,id)=>10+skill(c,id)+({advantage:5,disadvantage:-5,normal:0})[E.mode(c,'skill',id).mode]+E.sum(c,'passive.'+id);
function maxHP(c){let n=c.classes.reduce((s,x)=>s+x.hpRolls.reduce((a,r)=>a+Math.max(1,r+ability(c,'con')),0),0);if(c.subrace==='hill-dwarf')n+=level(c);if(c.classes.some(x=>x.id==='sorcerer'&&x.subclass==='draconic'))n+=classLevel(c,'sorcerer');n=Math.max(1,E.value(c,'hp.max',n));return c.exhaustion>=4?Math.floor(n/2):n;}
function armor(c){const worn=c.inventory.filter(x=>x.equipped&&x.quantity>0),body=worn.find(x=>x.armor_class&&x.armor_category!=='Shield'),shield=worn.find(x=>x.armor_category==='Shield'),p=proficiencies(c);const untrained=!!(body&&!p.includes('all-armor')&&!p.includes(body.armor_category.toLowerCase()+'-armor')||shield&&!p.includes('shields'));let n=10+ability(c,'dex'),formula='10 + DEX';if(body){const b=body.armor_class;n=b.base+(b.dex_bonus?Math.min(ability(c,'dex'),b.max_bonus??Infinity):0);formula=body.name+(b.dex_bonus?' + DEX'+(b.max_bonus!=null?' (макс. '+b.max_bonus+')':''):'');}else{if(c.classes[0].id==='barbarian'){n=Math.max(n,10+ability(c,'dex')+ability(c,'con'));formula='10 + DEX + CON'}if(c.classes[0].id==='monk'&&!shield){n=Math.max(n,10+ability(c,'dex')+ability(c,'wis'));formula='10 + DEX + WIS'}if(c.classes.some(x=>x.subclass==='draconic'))n=Math.max(n,13+ability(c,'dex'));}if(shield){n+=shield.armor_class.base;formula+=' + щит'}if(body&&c.choices?.fightingStyle==='defense')n++;return {body,shield,untrained,ac:E.value(c,'ac',n),formula};}
function weight(c){return c.inventory.reduce((s,i)=>s+(+i.weight||0)*i.quantity,0)+Object.values(c.coins).reduce((s,n)=>s+n,0)/50}function encumbrance(c){const w=weight(c),s=score(c,'str');return {weight:w,capacity:s*15,heavy:c.settings.encumbrance==='variant'&&w>s*10,light:c.settings.encumbrance==='variant'&&w>s*5,over:w>s*15};}
function speed(c){let n=C.get('races',c.race)?.speed||30;const ar=armor(c),en=encumbrance(c);if(classLevel(c,'barbarian')>=5&&ar.body?.armor_category!=='Heavy')n+=10;const m=classLevel(c,'monk');if(m>=2&&!ar.body&&!ar.shield)n+=10+Math.floor((m-2)/4)*5;if(ar.body?.str_minimum>score(c,'str')&&c.race!=='dwarf')n-=10;if(en.heavy)n-=20;else if(en.light)n-=10;n=E.value(c,'speed',n);if(c.exhaustion>=2)n=Math.floor(n/2);if(c.exhaustion>=5||['grappled','restrained','paralyzed','petrified','stunned','unconscious'].some(x=>E.has(c,x))||en.over&&c.settings.encumbrance!=='off')n=0;return Math.max(0,n)}
const initiative=c=>ability(c,'dex')+(classLevel(c,'bard')>=2?Math.floor(prof(c)/2):0)+E.sum(c,'initiative');
function slots(c){const casters=c.classes.filter(x=>['bard','cleric','druid','sorcerer','wizard'].includes(x.id)||['paladin','ranger'].includes(x.id)&&x.level>=2);const n=casters.reduce((s,x)=>s+(['paladin','ranger'].includes(x.id)?Math.floor(x.level/2):x.level),0);const sc=casters.length===1?C.level(casters[0].id,casters[0].level).spellcasting:C.level('wizard',n).spellcasting;return Array.from({length:9},(_,i)=>sc?.['spell_slots_level_'+(i+1)]||0)}
function pact(c){const n=classLevel(c,'warlock');return {level:n?Math.min(5,Math.ceil(n/2)):0,max:n>=17?4:n>=11?3:n>=2?2:n?1:0}}
function casting(c,id){const cl=C.get('classes',id),l=classLevel(c,id),a=cl?.spellcasting?.spellcasting_ability?.index||'int',sc=C.level(id,l).spellcasting||{};return {ability:a,mod:ability(c,a),attack:ability(c,a)+prof(c)+E.sum(c,'spell.attack'),dc:8+ability(c,a)+prof(c)+E.sum(c,'spell.dc'),cantrips:sc.cantrips_known||0,known:sc.spells_known||0,prepared:['cleric','druid','wizard'].includes(id)?Math.max(1,l+ability(c,a)):id==='paladin'?Math.max(1,Math.floor(l/2)+ability(c,a)):0,maxLevel:id==='warlock'?pact(c).level:Math.max(0,...Array.from({length:9},(_,i)=>sc['spell_slots_level_'+(i+1)]?i+1:0))};}
function weapon(c,w,ctx={}){const props=(w.properties||[]).map(x=>x.index),monk=classLevel(c,'monk'),ar=armor(c),martial=monk&&!ar.body&&!ar.shield&&(w.index==='unarmed'||w.index==='shortsword'||w.weapon_category==='Simple'&&w.weapon_range==='Melee'&&!props.includes('two-handed')&&!props.includes('heavy'));let a=w.weapon_range==='Ranged'?'dex':'str';if(props.includes('finesse')||martial)a=ability(c,'dex')>ability(c,'str')?'dex':'str';const p=proficiencies(c),plural={'crossbow-light':'crossbows-light','crossbow-hand':'hand-crossbows','crossbow-heavy':'crossbows-heavy',quarterstaff:'quarterstaffs'}[w.index]||w.index+'s',trained=w.index==='unarmed'||p.includes(plural)||p.includes(w.index)||p.includes(w.weapon_category?.toLowerCase()+'-weapons');let dice=ctx.twoHands&&w.two_handed_damage?w.two_handed_damage.damage_dice:w.damage?.damage_dice||'1';if(martial){const sides=monk>=17?10:monk>=11?8:monk>=5?6:4;if(!dice.includes('d')||Number(dice.split('d')[1])<sides)dice='1d'+sides}let b=ability(c,a),damage=b+(w.bonus||0);if(ctx.offhand&&b>0&&c.choices?.fightingStyle!=='two-weapon-fighting')damage=0;if(c.choices?.fightingStyle==='dueling'&&w.weapon_range==='Melee'&&!ctx.twoHands&&!ctx.offhand)damage+=2;if(E.active(c).some(x=>x.id==='rage')&&a==='str'&&w.weapon_range==='Melee')damage+=classLevel(c,'barbarian')>=16?4:classLevel(c,'barbarian')>=9?3:2;return {ability:a,trained,attack:b+(trained?prof(c):0)+(w.bonus||0)+(c.choices?.fightingStyle==='archery'&&w.weapon_range==='Ranged'?2:0)+E.sum(c,'attack'),dice,damage:damage+E.sum(c,'damage'),type:w.damage?.damage_type?.index||'bludgeoning',props};}
function features(c){const ids=[];for(const x of c.classes)for(let i=1;i<=x.level;i++){ids.push(...(C.level(x.id,i).features||[]).map(f=>f.index));if(x.subclass)ids.push(...(C.level(x.subclass,i).features||[]).map(f=>f.index));}ids.push(...(c.featureChoices||[]));return [...new Set(ids)].map(id=>C.get('features',id)).filter(Boolean)}
function resources(c){const out=[],add=(id,name,max,recharge)=>{if(max>0)out.push({id,name,max,recharge,used:c.resourceUsed[id]||0})},f=classLevel(c,'fighter'),b=classLevel(c,'barbarian'),m=classLevel(c,'monk'),p=classLevel(c,'paladin'),br=classLevel(c,'bard'),s=classLevel(c,'sorcerer'),cl=classLevel(c,'cleric'),d=classLevel(c,'druid'),w=classLevel(c,'wizard');if(f)add('second-wind','Второе дыхание',1,'short');if(f>=2)add('action-surge','Всплеск действий',f>=17?2:1,'short');if(f>=9)add('indomitable','Несгибаемый',f>=17?3:f>=13?2:1,'long');if(b)add('rage','Ярость',b===20?99:b>=17?6:b>=12?5:b>=6?4:b>=3?3:2,'long');if(m>=2)add('ki','Ци',m,'short');if(p){add('lay-on-hands','Наложение рук',p*5,'long');add('divine-sense','Божественное чувство',Math.max(1,1+ability(c,'cha')),'long')}if(br)add('bardic-inspiration','Вдохновение барда',Math.max(1,ability(c,'cha')),br>=5?'short':'long');if(s>=2)add('sorcery','Единицы чародейства',s,'long');if(cl>=2)add('channel-divinity','Божественный канал',cl>=18?3:cl>=6?2:1,'short');else if(p>=3)add('channel-divinity','Божественный канал',1,'short');if(d>=2)add('wild-shape','Дикий облик',d>=20?99:2,'short');if(w)add('arcane-recovery','Магическое восстановление',1,'dawn');if(c.race==='half-orc')add('relentless-endurance','Непоколебимая стойкость',1,'long');if(c.race==='dragonborn')add('breath','Дыхание дракона',1,'short');for(const x of c.customResources)out.push({...x,used:c.resourceUsed[x.id]||0});return out}
function canMulticlass(c,id){return [...new Set([...c.classes.map(x=>x.id),id])].every(k=>{const m=C.get('classes',k)?.multi_classing;return (m?.prerequisites||[]).every(p=>score(c,p.ability_score.index)>=p.minimum_score)&&(!m?.prerequisite_options||(m.prerequisite_options.from.options||[]).filter(p=>score(c,p.ability_score.index)>=p.minimum_score).length>=m.prerequisite_options.choose)})}
const attacks=c=>Math.max(1,...c.classes.map(x=>x.id==='fighter'?(x.level>=20?4:x.level>=11?3:x.level>=5?2:1):['barbarian','monk','paladin','ranger'].includes(x.id)&&x.level>=5?2:1));
return {mod,level,classLevel,prof,score,ability,proficiencies,skill,save,passive,maxHP,armor,weight,encumbrance,speed,initiative,slots,pact,casting,weapon,features,resources,canMulticlass,attacks};})();
