'use strict';
DND.Storage=(()=>{const Ch=DND.Character,KEY='dnd-companion-v4';let db=null,state=null,backend='';const fresh=()=>({schemaVersion:4,characters:[],active:null,packs:[],theme:'system',undo:[],backups:[]});
function migrate(c){if(c.schemaVersion===4)return Ch.validate(c);if(c.meta?.rulesEdition!=='5e-2014'||c.meta?.schemaVersion>3)throw Error('Неизвестная версия персонажа');const old=Ch.clone(c),first=c.progression.classes[0],n=Ch.create({name:c.identity.name,classId:first.classId,abilities:c.abilities.base,mode:c.meta.mode||'strict'});n.id=c.meta.id||Ch.uid();n.notes=(c.identity.notes||'')+'\nИмпорт v3: исходные данные сохранены в поле legacySource. Проверьте особенности и заклинания.';n.classes=c.progression.classes.map((x,i)=>{const die=DND.Content.get('classes',x.classId)?.hit_die||10,hd=c.health.hitDice?.['d'+die];return {id:x.classId,level:x.level,subclass:x.subclassId||'',hpRolls:Array.from({length:x.level},(_,j)=>i===0&&j===0?die:Math.floor(die/2)+1),hdUsed:hd?hd.maximum-hd.remaining:0}});n.skills=c.proficiencies.skills||{};n.proficiencies=(c.proficiencies.savingThrows||[]).map(x=>'saving-throw-'+x);n.choices.fightingStyle=c.progression.fightingStyle;n.hp=c.health.currentHP;n.tempHP=c.health.temporaryHP||0;n.death={success:c.health.deathSaves?.successes||0,failure:c.health.deathSaves?.failures||0,stable:!!c.health.deathSaves?.stable,dead:!!c.health.deathSaves?.dead};n.effects.push({id:Ch.uid(),name:'Коррекция HP из v3',target:'hp.max',operation:'add',value:c.health.maxHPBase-DND.Rules.maxHP(n),duration:'permanent'});n.inventory=(c.inventory.items||[]).map(x=>{let id=({'light-crossbow':'crossbow-light',leather:'leather-armor','scale-mail':'scale-mail'})[x.id]||x.id;let i;try{i=Ch.item(id,x.quantity||1)}catch{i={uid:Ch.uid(),index:id,name:x.name,quantity:x.quantity||1,weight:x.weight||0,effects:[]}}i.equipped=!!x.equipped;return i});n.conditions=(c.conditions||[]).map(x=>typeof x==='string'?x:x.id).filter(Boolean);for(const r of c.resources||[]){if(!DND.Rules.resources(n).some(x=>x.id===r.id))n.customResources.push({id:r.id,name:r.name,max:r.maximum,recharge:r.recovery?.includes('shortRest')?'short':'long'});n.resourceUsed[r.id]=r.maximum-r.current}if(c.concentration?.active)n.concentration={id:c.concentration.spellId,name:c.concentration.spellName,remaining:null};const sc=c.spellcasting;if(sc)n.spells[first.classId]={known:[...(sc.cantripsKnown||[]),...(sc.spellbook||sc.spellsKnown||[])],prepared:[...new Set([...(sc.prepared||sc.preparedSpells||[]),...(sc.alwaysPrepared||[])])]};if(sc)for(const [level,slot]of Object.entries(sc.slots||{}))n.slotsUsed[Number(level)-1]=Math.max(0,slot.maximum-slot.current);n.legacySource=old;return Ch.validate(n);}
async function init(){try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open(KEY,1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});backend='IndexedDB';state=await new Promise((resolve,reject)=>{const r=db.transaction('state').objectStore('state').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}catch{backend='localStorage';try{state=Ch.parse(localStorage.getItem(KEY)||'null')}catch(err){if(err.name!=='SecurityError')throw err}}state??=fresh();if(state.schemaVersion!==4)throw Error('Неизвестная версия базы. Импортируйте резервный JSON.');DND.Content.setPacks(state.packs);return state;}
async function save(){state.savedAt=new Date().toISOString();if(db)await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(Ch.clone(state),'main');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Сохранение отменено'))});else localStorage.setItem(KEY,JSON.stringify(state));}
const snapshot=()=>Ch.clone({characters:state.characters,active:state.active,packs:state.packs,theme:state.theme});async function change(fn){const before=snapshot(),undo=state.undo.slice();try{const result=await fn(state);state.undo.push(before);state.undo=state.undo.slice(-30);DND.Content.setPacks(state.packs);await save();return result}catch(e){Object.assign(state,before);state.undo=undo;DND.Content.setPacks(state.packs);throw e}}
async function undo(){if(!state.undo.length)throw Error('Нет действий для отмены');const before=snapshot(),u=state.undo.pop();try{Object.assign(state,u);DND.Content.setPacks(state.packs);await save()}catch(e){Object.assign(state,before);state.undo.push(u);throw e}}
function exportData(all=true,c=null){return all?{app:'DND Companion 2014',schemaVersion:4,exportedAt:new Date().toISOString(),characters:state.characters,packs:state.packs}:c||active()}
async function importData(text){const data=Ch.parse(text);const chars=(data.characters||[data]).map(migrate);const packs=(data.packs||[]).map(DND.Content.validatePack);return change(s=>{for(const p of packs){const exists=s.packs.find(x=>x.id===p.id);if(exists&&JSON.stringify(exists.content)!==JSON.stringify(p.content))throw Error('Конфликт пакета '+p.id);if(!exists)s.packs.push(p)}for(const c of chars){c.id=Ch.uid();c.name+=' (импорт)';s.characters.push(c)}s.active=chars[0]?.id||s.active;return chars.length})}
async function backup(){return change(s=>{s.backups.unshift({at:new Date().toISOString(),data:snapshot()});s.backups=s.backups.slice(0,3)})}async function restore(i){const b=state.backups[i];if(!b)throw Error('Резервная копия отсутствует');return change(s=>Object.assign(s,Ch.clone(b.data)))}const active=()=>state.characters.find(c=>c.id===state.active);
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
return {init,save,change,undo,backup,restore,active,migrate,importData,exportData,download,get state(){return state},get backend(){return backend}};})();
